pipeline {
    agent {
         docker {
      image 'abhishekf5/maven-abhishek-docker-agent:v1'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
    } // we chose to use docker agent considering its avantages
         
    }
    tools{
        maven 'Maven'
    }
    
    stages {
        stage ("checkout"){
            steps {
            
            sh "echo passed"
            checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/MalickReborn/Continuous-Integration-with-Springboot-Microservices.git']])
        } 
        }
        stage('Build and test') {
            steps {
                sh 'ls -ltr'
                // build the project and create a JAR file
                sh  'cd user-service && mvn clean package'
            }
        }
        
        stage("Static Code Analysis"){
            environment {
                 SONAR_URL = "http://192.168.1.12:9000/"} // we have opted here for a docker container as a sonarqube server
                 steps{
                     withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
          sh 'cd user-service && mvn sonar:sonar -Dsonar.login=${SONAR_AUTH_TOKEN} -Dsonar.host.url=${SONAR_URL}'
        }       
                 }
            
        }
        
        stage('Build and Push Docker Image') {
      environment {
        DOCKER_IMAGE = "malickguess/ultimate-cicd:${BUILD_NUMBER}"
        // DOCKERFILE_LOCATION = "Springboot-Microservice-deployment-test-on-k8s/user-service/Dockerfile"
        REGISTRY_CREDENTIALS = credentials('dockerhub')
      }
      steps {
        script {
            sh 'cd user-service && docker build -t ${DOCKER_IMAGE} .'
            def dockerImage = docker.image("${DOCKER_IMAGE}")
            docker.withRegistry('https://index.docker.io/v1/', "dockerhub") {
                dockerImage.push()
            }
        }
      }
    }
    }
}
